### ISSUE TITLE
suggested revisions to overarching phers function

### ISSUE THREAD

**Issue by jakejh** [hugheylab/phers#42]
1. Change name to simply `phers()`.
2. Remove argument diseaseIds. The same effect can be achieved by simply subsetting the diseasePhecodeMap.
3. Add argument for weights, which is NULL by default, which means calculate weights based on provided data.
4. Have function return a named list of phecodeOccurrences, weights, and scores.
5. Add argument for formula for calculating residual scores, which is NULL by default. If not NULL, the scores table has an additional column resid_score.

https://github.com/hugheylab/phers/blob/b9c3189aa469568616977b7c3b42ee3752f6584d/R/phers.R#L198-L200

**Comment by arefnel** [comment]
shouldn't the weights argument be true/false since the only other option is to use our weights?

**Comment by jakejh** [comment]
I don't think so. What if someone wants to calculate scores for a few patients from their institution, and to use weights based on all patients at their institution?

**Comment by arefnel** [comment]
Yeah you're right! They could even have a weight file saved and load that instead of having to calculate it every time.

**Comment by arefnel** [comment]
61633729b5a8c75c8f8ea2b3fb66a1f8fdadf721
