### ISSUE TITLE
using ignore_attr in tests

### ISSUE THREAD

**Issue by arefnel** [hugheylab/phers#46]
https://github.com/hugheylab/phers/blob/afb19f31599dba2c9fbdff5b06d724c7c95a0b5a/tests/testthat/test_phers.R#L88

Whenever a data.table is created from a merge,  this shows up in its attributes: `attr(*, "sorted")= chr`. I'm not sure if there's another way around this other than using `ignore_attr = TRUE`

**Comment by jakejh** [comment]
I see, ok, let's leave it for now.
