### ISSUE TITLE
using nomatch for the anti join in getPhecodeOccurrences()

### ISSUE THREAD

**Issue by arefnel** [hugheylab/phers#47]
https://github.com/hugheylab/phers/blob/afb19f31599dba2c9fbdff5b06d724c7c95a0b5a/R/phers.R#L54

I remember you said I need to use nomatch here. I think I got it to work without it. Wasn't sure what nomatch does and couldn't find any documentation for it. here's an example code:

```
aa = data.table(a = c(1,2,3), b = c(4,5,6), c = c(1,2,1))
bb = data.table(b = c(4,5,8), c = c(1,2,9))
aa[!bb, on = c('b', 'c')]
```

**Comment by jakejh** [comment]
I think you're right, the `nomatch` argument is not needed for the anti-join version.
