### ISSUE TITLE
changing error message for assertSubset()

### ISSUE THREAD

**Issue by arefnel** [hugheylab/phers#48]
https://github.com/hugheylab/phers/blob/afb19f31599dba2c9fbdff5b06d724c7c95a0b5a/R/utils.R#L24-L25

Do you think it's a good idea to change the error message here? "person_id in phecodeOccurrences needs to be a subset of demos" instead of having it list all of the person IDs?

**Comment by jakejh** [comment]
That's a good idea. Something like "`phecodeOccurrences$person_id` should be a subset of `demos$person_id`."

**Comment by jakejh** [comment]
And maybe list only the person_ids that are in phecodeOccurrences but not in demos.

**Comment by arefnel** [comment]
b66f5a67f372537a3cc9cd13820aab480d6bd16b
